version: "3.3"

services:
  icarus-mqtt-broker:
    image: eclipse-mosquitto
    container_name: icarus-mqtt-broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  icarus-mjpeg-streamer:
    build:
      context: mjpeg_streamer
      dockerfile: dockerfile
    container_name: icarus-mjpeg_streamer
    ports:
      - 5000:5000
      - 6000:6000
    command:
      - python3
      - -m
      - src.app